### ISSUE TITLE
JsonStringEnumConverter attribute is not working when global JsonStringEnumConverter is registered globally

### ISSUE THREAD

**Issue by Sebosek** [Macross-Software/core#1]
Hi,

thanks for JsonStringEnumConverter, it's what I was looking for. Unfortunately, the converter can't be used when _System.Text.Json.Serialization.JsonStringEnumConverter_ is registered globally.
Here is a [sample repository](https://github.com/Sebosek/EnumMemberBug).

There are two projects and a shared library with enums. The first project is called "Enums" and there is defined global _System.Text.Json.Serialization.JsonStringEnumConverter_. So, with that one can't use enum values as they are defined with the EnumMember attribute. The second project is called "EnumMembers" and there is no global enum converter registered, that is working as expected, but for enums without JsonConverter one must use numbers instead of a string.

We serialize and deserialize enums as strings, but sometimes (OpenID connect client registration) we need to follow the standard and use defined naming convention, so EnumMember attributes are in place and we don't want every enum to decorate with JsonConverter attribute.

Is there a way out?

**Comment by Sebosek** [comment]
Ok, just found a workaround... Basically, I need to either clear all filters and then add `JsonStringEnumMemberConverter` or replace `JsonStringEnumConverter` with `JsonStringEnumMemberConverter`...

**Comment by CodeBlanch** [comment]
@Sebosek Ya in your `Startup.ConfigureServices` if you replace...
```csharp
options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter(JsonNamingPolicy.CamelCase));
```
...with...
```csharp
options.JsonSerializerOptions.Converters.Add(new JsonStringEnumMemberConverter(JsonNamingPolicy.CamelCase));
```
...you should be good to go.

`JsonStringEnumMemberConverter` provides basically everything `JsonStringEnumConverter` does and then adds on top of it. _Should_ be safe to swap out the stock one with the extension version.

I don't think there's anything we can do to fix the selection should both end up registered. System.Text.Json will look for a converter in the options collection that `CanConvert` the type it's working on. First one it finds, it will use.
