### ISSUE TITLE
Handle mutable properties on the LogEvent

### ISSUE THREAD

**Issue by snakefoot** [Macross-Software/core#10]
The `FileLogger` converts the LogEvent into a `LoggerJsonMessage`:

https://github.com/Macross-Software/core/blob/74f37d674409b3deff39e00163585d3763131051/ClassLibraries/Macross.Logging.Files/Code/FileLogger.cs#L53

But be careful when the extracted properties are complex objects that can be mutable (ex disposed or returned to object pool after being logged). Then the output might not be like you expect, when the async-writer finally starts converting to the actual json-output.

**Comment by CodeBlanch** [comment]
Thanks @snakefoot. I updated the README with some guidance about the deferred serialization. It was definitely done intentionally but you are right, users should be advised so they don't get unexpected results. I'm open to suggestions (or contributions :smile:) for improvement, but I really want the JSON serialization to happen on the dedicated thread so the real application logic doesn't have to sit and wait for it. Devs can always manually serialize and then log the things that will mutate or be returned to pools immediately after being logged.
