### ISSUE TITLE
DateTime format doesn't match .Net Framework's JavaScriptSerializer or Json.Net's DateFormatHandling.MicrosoftDateFormat

### ISSUE THREAD

**Issue by terryaney** [Macross-Software/core#13]
In your Json extensions code, if I format CultureInfo's DateTimeFormat, the property MinSupportedDateTime comes out like this:

JavascriptSerializer/DateFormatHandling.Microsoft = "MinSupportedDateTime":"\/Date(-62135596800000)\/"

But with your code, it seems to come out like "MinSupportedDateTime":"/Date(-62135596800000)/" (missing the \ before /).  Will that still work as intended?

**Comment by CodeBlanch** [comment]
@terryaney I updated the code to add in the escape: https://github.com/Macross-Software/core/commit/b633d26356b37c911406868ee49483df1bd4b030. It was actually pretty hard to do! System.Text.Json automatically encodes any `\` as `\\` so I had to do some trickery to match the old format (`\/`).
