### ISSUE TITLE
Add option for ignoring invalid enum string values

### ISSUE THREAD

**Issue by The-MAZZTer** [Macross-Software/core#15]
It would be nice to have an option for ignoring failures to parse enum values, and setting the member to the default value or the 0 value instead.

Example use case:

I am parsing data from an external service and one of the values is a string value with a limited set of values. I use an enum in conjunction with JsonStringEnumMemberConverter in order to keep my code clean and ensure I don't typo any of those strings the 100s of times I am comparing them throughout the code.

One day the external service adds in a new string to the list of strings they use in this field. Due to what I am doing I don't care about data with this new value. As things are right now the JSON parsing would fail.

If I could indicate to JsonStringEnumMemberConverter I wanted it to ignore these errors and return a default/0 value instead, I could reserve enum value 0 to mean "invalid" and check for this value to determine if the value was not parsed (or potentially use a nullable enum and check for null) and ignore the specific object. In other scenarios I could try to recover or use partial data after detecting this case.

Workaround for now I will probably go with is for me to pull in the source code of JsonStringEnumMemberConverter directly and replace the throw statements with return statements casting 0 to the proper type.

**Comment by CodeBlanch** [comment]
@The-MAZZTer Thanks for the suggestion! I added this: https://github.com/Macross-Software/core/commit/4b9beccf8cf11f2a008185f3833c5f5ecebc7a43

Should be up on nuget any second as 2.1.0-beta1. If you wouldn't mind trying that out and letting me know what you think that would be helpful. Options are tricky with the attribute pattern but should work fine when used via `JsonSerializerOptions.Converters`.

**Comment by The-MAZZTer** [comment]
I would say having a single default ulong value doesn't make too much sense unless it's 0. If you have multiple enums you may want different fallback values for each, or fallback values on a member-by-member basis (not sure if this can be done).

Also I think flags should ignore invalid strings in this mode and bitwise or up recognized flags rather than reverting to the default value when it hits a flag it doesn't recognize. That said I can see scenarios where that logic would be desired.

What you've done is good enough for what I need (my use case I listed), so I guess it's just a matter of how you think it should be extended to more general use cases.

Let me specifically spell out what I would do, maybe you'll find this useful.

Not sure if converters have access to contextual information so I have two possible versions here:

1. If converters can determine the default value of a member (not sure if they can), eg  `private MyEnum foo = MyEnum.Bar;`, the default value should be assigned if the input string is invalid. If there are multiple flags, they should be used if any flag is valid, with invalid flags being skipped. If all flags are skipped, the default value is uses. Alternately the current approach of using the default value if any invalid strings are encountered is simpler logic but removes the ability to match partial flags.
2. If converters don't have access to the context to know the default value of a field, proceed as in 1 but assume the default value is null for nullable and 0 for non-nullable enums.

I'll test the current 2.1.0-beta1 this week probably, I'm currently working on other projects at work but I'm sure I'll get back to this this week.

**Comment by CodeBlanch** [comment]
@The-MAZZTer 

> I would say having a single default ulong value doesn't make too much sense unless it's 0. If you have multiple enums you may want different fallback values for each, or fallback values on a member-by-member basis (not sure if this can be done).

That options quirk is really from the [dotnet/runtime JsonStringEnumConverter](https://github.com/dotnet/runtime/blob/ec1897724f6dc5ab49eebde5f35292493e1bed7b/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonStringEnumConverter.cs#L40) it is based on. There's a factory, but only one set of options.

You're right, it isn't too useful, so I took a stab at providing an API to allow for options by enum: https://github.com/Macross-Software/core/commit/e83ab8a95068fba9c14c650a7eb4d25d8caa977d

With that commit you can solve the problem one of two ways...

* Directly on the enum:

    ```csharp
    [JsonStringEnumMemberConverterOptions(deserializationFailureFallbackValue: MyEnum.Unknown)]
    [JsonConverter(typeof(JsonStringEnumMemberConverter))]
    public enum MyEnum
    {
        Unknown = 0,

        [EnumMember(Value = "value1")]
        ValidValue = 1
    }
    ```

* Using `JsonSerializerOptions`:

    ```csharp
    JsonSerializerOptions options = new JsonSerializerOptions
    {
        Converters =
        {
            new JsonStringEnumMemberConverter(
                new JsonStringEnumMemberConverterOptions(deserializationFailureFallbackValue: DayOfWeek.Friday),
                typeof(DayOfWeek)),
            new JsonStringEnumMemberConverter(
                new JsonStringEnumMemberConverterOptions(deserializationFailureFallbackValue: 0),
                typeof(FlagDefinitions),
                typeof(EnumDefinition?)),
            new JsonStringEnumMemberConverter(allowIntegerValues: false)
        }
    };
    ```

Let me know what you think of that. I haven't pushed to nuget yet, going to look at your flags thing next.

**Comment by The-MAZZTer** [comment]
What you already had before is probably fine for my use case. Per-enum will probably be useful for cases such as where the enums themselves can't be modified (part of a different library, etc).

It sounds like you can't tell the deserializer to skip a member so it uses the default value assigned by the class, which would be the best way to handle it I think, since the fallback could then be set on the class member itself.

Anyway, I've said the way I would do it, your way is useful too and covers some use cases mine wouldn't. Either way my use case is satisfied... I'm happy. :) You can re-close this once you're happy with it.

**Comment by CodeBlanch** [comment]
@The-MAZZTer Sounds good! I tweaked the `[Flags]` behavior and pushed to NuGet.
