### ISSUE TITLE
Macross.Json.Extensions 2.1.0 Nuget

### ISSUE THREAD

**Issue by mprigge** [Macross-Software/core#22]
Hi! I see that there were several beta releases for Macross.Json.Extensions 2.1.0, but never a production release (at least not on NuGet Gallery). Was that an oversight or did you decide not to release 2.1.0 before proceeding into beta on 2.2.0?

**Comment by CodeBlanch** [comment]
Sorry @mprigge I realized after I bumped to 2.2.0-beta1 that I probably should have released a 2.1 stable. I want to give 2.2.0-beta1 a few days to soak out there and then I'm thinking I'll release a 2.2.0 stable. It will have everything from 2.1 with the addition of this new Utf8JsonStreamReader thing (I'm still working on a blog to introduce/explain that). OK waiting a few more days?

**Comment by mprigge** [comment]
Sure! Assuming 2.1.0-beta5 had everything 2.1.0 would have had, we can always use that if we're in a rush. I just wanted to make sure there wasn't some known issue in 2.1.0-beta5 you were considering reverting or something (I didn't see any suggestion of that, but thought it was a good idea to ask).

**Comment by kamranayub** [comment]
@CodeBlanch sorry to bump, but I just created a new package that depends on this and I'm running into issues installing my package because 2.2.0 (or 2.1.0) isn't yet in stable. I am using `JsonStringEnumMemberConverter` and `JsonStringEnumMemberConverterOptions`.

**Comment by CodeBlanch** [comment]
@kamranayub No problem! I just pushed out 2.2.0 it should be available in a few moments. No changes from 2.2.0-beta2, just dropped the prerelease tag.
