### ISSUE TITLE
The JSON value '/Date(-62135575200000-0600)/' could not be converted to System.DateTime

### ISSUE THREAD

**Issue by Malincoln9** [Macross-Software/core#26]
I get this error when trying to parse a json with the value "/Date(-62135575200000-0600)/" to a datetime.

**Comment by CodeBlanch** [comment]
@Malincoln9 Are you able to switch the target type to `DateTimeOffset`? The `JsonMicrosoftDateTimeConverter` doesn't understand the time offset in your JSON ("-0600") but `JsonMicrosoftDateTimeOffsetConverter` can handle that.

Example from the tests:

https://github.com/Macross-Software/core/blob/91fe767493ab962e6f6125a6acc3f78f149e9fe4/ClassLibraries/Macross.Json.Extensions/Test/JsonMicrosoftDateTimeOffsetConverterTests.cs#L52-L69

**Comment by Malincoln9** [comment]
I was able to make that work. Would have liked to keep it DateTime, but thanks.

**Comment by LeaFrock** [comment]
Same issue, but I cannot switch the target type to `DateTimeOffset`. Any workaround?

**Comment by CodeBlanch** [comment]
@LeaFrock Try something like this:

```csharp
		private static readonly JsonSerializerOptions s_ThingOptions = new()
		{
			Converters = { new JsonMicrosoftDateTimeWithOffsetConverter() }
		};

		public Thing ParseThingFromJson(string json)
		{
			return JsonSerializer.Deserialize<Thing>(json, s_ThingOptions);
		}

		public sealed class JsonMicrosoftDateTimeWithOffsetConverter : JsonConverterFactory
		{
			private readonly JsonMicrosoftDateTimeOffsetConverter _DateTimeOffsetFactory = new();

			public override bool CanConvert(Type typeToConvert) => typeToConvert == typeof(DateTime);

			public override JsonConverter CreateConverter(Type typeToConvert, JsonSerializerOptions options)
			{
				return new Converter(
					(JsonConverter<DateTimeOffset>)_DateTimeOffsetFactory.CreateConverter(typeof(DateTimeOffset), options));
			}

			private class Converter : JsonConverter<DateTime>
			{
				private readonly JsonConverter<DateTimeOffset> _DateTimeOffsetConverter;

				public Converter(JsonConverter<DateTimeOffset> dateTimeOffsetConverter)
				{
					_DateTimeOffsetConverter = dateTimeOffsetConverter;
				}

				public override DateTime Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
				{
					DateTimeOffset dateTimeOffset = _DateTimeOffsetConverter.Read(ref reader, typeToConvert, options);
					return dateTimeOffset.LocalDateTime;
				}

				public override void Write(Utf8JsonWriter writer, DateTime value, JsonSerializerOptions options)
					=> _DateTimeOffsetConverter.Write(writer, value, options);
			}
		}
```

What that will do is round-trip your values using local time.

If you read a value from the DB like `\/Date(1580803200000-0500)\/` on a system in the pacific timezone and then immediately wrote it back, it would be changed to `\/Date(1580803200000-0800)\/`. The reason for that is `DateTime` can't store the offset. It either has to be UTC or Local.

If all your systems are in the same time zone, that should work fine. If your system are not, I recommend switching your ORM to `DateTimeOffset` because that is what it is for 😄 Sounds like the current design might be bugged.

**Comment by paritoshgote-msft** [comment]
Spoke offline with @CodeBlanch who is going to create a PR against this issue.

After looking at the DataContractJson docs, we see that "/Date(700000+0500)/" is actually a DateTime format and not DateTimeOffset format. So JsonMicrosoftDateTimeConverter should be handling this case. If there is any +/- offset it's deserialized to local time; if not, it's deserialized to UTC

https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/stand-alone-json-serialization#datetime-wire-format

"The part that consists of "+0500" in the example is optional and indicates that the time is of the Local kind - that is, should be converted to the local time zone on deserialization. If it is absent, the time is deserialized as Utc. The actual number ("0500" in this example) and its sign (+ or -) are ignored."

**Comment by CodeBlanch** [comment]
[3.0.0-beta2](https://www.nuget.org/packages/Macross.Json.Extensions/3.0.0-beta2) has been published which updates `JsonMicrosoftDateTimeConverter` to follow the spec linked above.
