### ISSUE TITLE
JsonStringEnumMemberConverter: Enums cannot be used as dictionary keys

### ISSUE THREAD

**Issue by felschr** [Macross-Software/core#27]
#### Issue:
When using an enum with `JsonStringEnumMemberConverter` as a dictionary key it'll fail:
```
The type 'App.MyEnum' is not a supported dictionary key using converter of type 'System.Text.Json.Serialization.JsonStringEnumMemberConverter+EnumMemberConverter`1[App.MyEnum]'.
```

#### Reproduction:
The enum & class to reproduce this:
```cs
[JsonConverter(typeof(JsonStringEnumMemberConverter))]
public enum MyEnum
{
    [EnumMember(Value = "one")]
    One = 1,
    [EnumMember(Value = "two")]
    Two = 2,
}

public class MyModel
{
    [JsonPropertyName("stuff")]
    public IDictionary<MyEnum, string> Stuff { get; set; }
}
```

#### Suggested solution:
`ReadAsPropertyName()` & `WriteAsPropertyName()` need to be added to the converter to fix this: https://github.com/dotnet/runtime/issues/46520#issuecomment-896196155

**Comment by CodeBlanch** [comment]
@felschr Thanks for this! It should work now in [3.0.0-beta1](https://www.nuget.org/packages/Macross.Json.Extensions/3.0.0-beta1). Going to close the issue but feel free to reopen if needed.
