### ISSUE TITLE
BufferWriter should not be static

### ISSUE THREAD

**Issue by snakefoot** [Macross-Software/core#9]
Think it should just be `private readonly`:

https://github.com/Macross-Software/core/blob/74f37d674409b3deff39e00163585d3763131051/ClassLibraries/Macross.Logging.Files/Code/FileLoggerProvider.cs#L23

If having multiple `FileLoggerProvider`-instances then it will generate unexpected output. Ex. if having multiple Host-instances, or if one day adding support for multiple files within the same host.

**Comment by CodeBlanch** [comment]
Thank you for the excellent suggestion! Code has been updated.
